### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by RandomPolishMan** [JojocraftTv/Discord-Token-Grabber-Java#5]
Good afternoon.

I wanted to know more clearly what are the steps I need to take in order to run the code smoothly, what are the pre-requirements to run it and if it works on Ubuntu Linux.

Thanks for your time.

**Comment by JojocraftTv** [comment]
Hey RandomPolishMan,

1. How to use it?

- Open the Grabber.java file, and copy it into a new class in your Java-Project.
- Include the 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File)
- To get the Discord-Tokens call getTokens() this will return a java String list with all the found tokens


2. What are the Requirements?

- 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File, note that the linked dependencies version may be outdated.)


3. Does it work on Linux?

- With some extra steps, yes. The Code will run on Linux, you just need to add the Paths to the Discord leveldb Folder.

Also note if you want to use it for all Discord Versions (like PBT and Canary) you will need to add the Paths as well.

If you're facing Problems with changing the Code, just reply and If I find some time I might be able to update the Grabber to work on all Discord Versions and most OS's.

For Legal Reasons: This is just for Educational proposes only, using Discord-Token grabbers is against Discord Terms of Service, and you take full responsibility for your own actions.

**Comment by Simeonya** [comment]
> Hey RandomPolishMan,
> 
> 1. How to use it?
> 
> * Open the Grabber.java file, and copy it into a new class in your Java-Project.
> * Include the 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File)
> * To get the Discord-Tokens call getTokens() this will return a java String list with all the found tokens
> 
> 2. What are the Requirements?
> 
> * 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File, note that the linked dependencies version may be outdated.)
> 
> 3. Does it work on Linux?
> 
> * With some extra steps, yes. The Code will run on Linux, you just need to add the Paths to the Discord leveldb Folder.
> 
> Also note if you want to use it for all Discord Versions (like PBT and Canary) you will need to add the Paths as well.
> 
> If you're facing Problems with changing the Code, just reply and If I find some time I might be able to update the Grabber to work on all Discord Versions and most OS's.
> 
> For Legal Reasons: This is just for Educational proposes only, using Discord-Token grabbers is against Discord Terms of Service, and you take full responsibility for your own actions.

I would say you should possibly write this into the README

**Comment by RandomPolishMan** [comment]
> Hey RandomPolishMan,
> 
>     1. How to use it?
> 
> 
>     * Open the Grabber.java file, and copy it into a new class in your Java-Project.
> 
>     * Include the 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File)
> 
>     * To get the Discord-Tokens call getTokens() this will return a java String list with all the found tokens
> 
> 
>     2. What are the Requirements?
> 
> 
>     * 2 Maven Dependencies: jna-platform and org.json (linked in the Readme-File, note that the linked dependencies version may be outdated.)
> 
> 
>     3. Does it work on Linux?
> 
> 
>     * With some extra steps, yes. The Code will run on Linux, you just need to add the Paths to the Discord leveldb Folder.
> 
> 
> Also note if you want to use it for all Discord Versions (like PBT and Canary) you will need to add the Paths as well.
> 
> If you're facing Problems with changing the Code, just reply and If I find some time I might be able to update the Grabber to work on all Discord Versions and most OS's.
> 
> For Legal Reasons: This is just for Educational proposes only, using Discord-Token grabbers is against Discord Terms of Service, and you take full responsibility for your own actions.

Good afternoon,

I would be happy if you could adapt the code to work on Ubuntu Linux, as I'm not a Java coder.

For my information:
1) How does the tool work? I saw in README.md that it just gets the encrypted version of the token somewhere, but I didn't understand the full process. Will it create an executable file the target must run in order to get the token, is the process fully remote, etc.
2) How can I assure your code is safe to use?
3) Do you have any other way I can contact you (discord, telegram, etc.)? 

Thanks again for your time.

**Comment by JojocraftTv** [comment]
Hey again,

If I find some time this week, I can update the code to work on Linux as well.

How does the tool work?

1. It tries to open the Local State file in Discord's Appdata folder.
2. It parses the file as a JSON file and gets the value of os_crypt.encrypted_key which is the Encryption/Deception key of the token.
3. Now it looks through all files in the Discord's leveldb folder and tries to find matches with a regex. All the results will be added to a list.
4. The key will now be Base64 decoded to get the raw byte array for the decryption process.
5. The raw bytes will be slightly modified in order to work with the Java Crypto Module.
6. Now the token will be decrypted with "AES/GCM/NoPadding" 
7. Now the function just returns a list with all the tokens found.

That was the basic process; the code does not include sending the token, etc.

Note: The file needs to be executed on the target machine. 
It's possible to pack a Java program into an executable file. But if you want to have a.exe, I would recommend using C# or C++. 
I designed this grabber for Java applications and modifications for games like Minecraft, which use Java.



How can you be sure my code is safe?

You can look at it or run it in a VM.
The code is not that complicated, even for people who only have a small knowledge of Java. 


Can you contact me anywhere else?

Yes you can. 
There are a few options:

    E-Mail: support@jojocrafttv.de
    Discord: @Jojocrafttv
    Twitter: @Jojocraft_Tv
    Telegram: @JojocraftTv

I hope I could answer your questions.
